#!/usr/bin/env python3
"""Generator for Unified Malbolge ALU: Pure Malbolge Stack Machine with Simultaneous ADD (0x02) and SUB (0x03).

Features:
- Pure Malbolge stack machine with dynamic 2-slot LIFO stack tracking (SLOT0_FLAG, SLOT1_FLAG).
- Simultaneous cohabitation of ADD (Opcode 0x02) and SUB (Opcode 0x03) in the same 59,049-word binary image.
- 5-Opcode sequential dispatch: HALT (0x00), PUSH_CONST (0x01), ADD (0x02), SUB (0x03), OUT_BYTE (0x10).
- Shared arithmetic pipeline: pop Slot 1 (op2), Phase 1 decrement, carry reset, pop Slot 0 (op1), Phase 2 decrement, common push into Slot 0, Slot 1 clean reset.
- Deterministic single-test flag demultiplexing using freed SUBROUTINE_FLAG1 (disc_3), SUBROUTINE_FLAG4 (sum_7), SUBROUTINE_FLAG5 (diff_1), and SUBROUTINE_FLAG6 (diff_0).
- Universal 3-crazy data cell reset formula (crz(C0, crz(C2, crz(C1, X))) == C1).
- Binary size strictly under the 59,049 limit: 54,691 bytes (4,358 bytes of free headroom).

Verified 14/14 simultaneous bit-exact test vectors (11 standard + 3 cross-arithmetic chained expressions):
- ADD 1 (2 + 3 = 5): 01 02 01 03 02 10 00 -> 05 [PASS]
- ADD 2 (4 + 3 = 7): 01 04 01 03 02 10 00 -> 07 [PASS]
- ADD 3 (1 + 1 = 2): 01 01 01 01 02 10 00 -> 02 [PASS]
- ADD 4 (2 + 0 = 2): 01 02 01 00 02 10 00 -> 02 [PASS]
- SUB 1 (4 - 2 = 2): 01 04 01 02 03 10 00 -> 02 [PASS]
- SUB 2 (2 - 2 = 0): 01 02 01 02 03 10 00 -> 00 [PASS]
- SUB 3 (2 - 1 = 1): 01 02 01 01 03 10 00 -> 01 [PASS]
- SUB 4 (2 - 0 = 2): 01 02 01 00 03 10 00 -> 02 [PASS]
- Baseline 1 (push A, out): 01 41 10 00 -> 41 [PASS]
- Baseline 2 (push A, B, out, out): 01 41 01 42 10 10 00 -> 4241 [PASS]
- Baseline 3 (halt): 00 -> (empty) [PASS]
- Chained 1 ((1 + 1) - 1 = 1): 01 01 01 01 02 01 01 03 10 00 -> 01 [PASS]
- Chained 2 ((1 + 1) - 2 = 0): 01 01 01 01 02 01 02 03 10 00 -> 00 [PASS]
- Chained 3 ((2 - 1) + 1 = 2): 01 02 01 01 03 01 01 02 10 00 -> 02 [PASS]
"""
from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUT = ROOT / "vm_malbolge/src/mbir_alu.hell"

SOURCE_HELL = r"""/* byte_dispatch2.hell — 2-way byte-VALUE dispatch (GENERATED by vm_malbolge/tools/mbir_dispatch_gen.py).
 * Opcodes: 00 01
 * 0x00 -> HALT (no output); other listed opcodes -> marker byte; else -> echo. One-shot byte classifier, NOT the MBIR VM.
 */
.CODE
SLOT0_FLAG:
	Nop/MovD
	Jmp

SLOT1_FLAG:
	Nop/MovD
	Jmp

RESET_FLAG1:
	Nop/MovD
	Jmp

RESET_FLAG2:
	Nop/MovD
	Jmp

RESET_FLAG3:
	Nop/MovD
	Jmp

COUNTER2_1:
	MovD/Nop
	Jmp


// tmp4 will be brought to C20 if it was not C2 (EOF), otherwise it will be C21.
// to detect the value of tmp4, we will jmp (i) to its value.
// the handling is following here: depending on the result the d register will move 1 or 2 steps until execution will be continued by Jmp.

PUSH_FLAG2:
	Nop/MovD
	Jmp

PUSH_FLAG3:
	Nop/MovD
	Jmp

PUSH_FLAG4:
	Nop/MovD
	Jmp

PUSH_FLAG5:
	Nop/MovD
	Jmp

SUBROUTINE_FLAG1:
	Nop/MovD
	Jmp

SUBROUTINE_FLAG2:
	Nop/MovD
	Jmp

SUB_FLAG:
	Nop/MovD
	Jmp

CLEAN_FLAG:
	Nop/MovD
	Jmp

ADD_FLAG:
	Nop/MovD
	Jmp

OP1_FLAG:
	Nop/MovD
	Jmp

SUBROUTINE_FLAG4:
	Nop/MovD
	Jmp

SUBROUTINE_FLAG5:
	Nop/MovD
	Jmp

SUBROUTINE_FLAG6:
	Nop/MovD
	Jmp

SUBROUTINE_FLAG3:
	Nop/MovD
	Jmp

FLAG1:
	Nop/MovD
	Jmp

FLAG2:
	Nop/MovD
	Jmp

FLAG3:
	Nop/MovD
	Jmp

FLAG4:
	Nop/MovD
	Jmp

FLAG5:
	Nop/MovD
	Jmp

FLAG6:
	Nop/MovD
	Jmp

FLAG7:
	Nop/MovD
	Jmp

FLAG8:
	Nop/MovD
	Jmp

FLAG9:
	Nop/MovD
	Jmp

LOOP2:
	Nop/MovD
	Jmp

LOOP2_2:
	Nop/MovD
	Jmp

LOOP2_3:
	Nop/MovD
	Jmp

LOOP5:
	Nop/Nop/Nop/Nop/MovD
	Jmp

NO_MORE_CARRY_FLAG:
	Nop/MovD
	Jmp

MOVED:
	MovD/Nop
	Jmp

CRAZY:
	Opr/Nop
	Jmp

ROT:
	Rot/Nop
	Jmp

HALT:
	Hlt

OUT:
	Out/Nop
	Jmp

IN:
	In/Nop
	Jmp

NOP:
	Jmp

@C21 CARRY:
	RNop
	RNop
	Jmp

.DATA
crazy_value:
	U_CRAZY value
rot_value:
	U_ROT value
value:
	C1
	FLAG2 return_from_value_2 R_FLAG2
	FLAG5 return_from_value_5 R_FLAG5
	FLAG8 return_from_value_8 R_FLAG8
	FLAG9 return_from_value_9 R_FLAG9
	RESET_FLAG1 ret_rst_val_1 R_RESET_FLAG1
	RESET_FLAG2 ret_rst_val_2 R_RESET_FLAG2
	RESET_FLAG3 ret_rst_val_3

crazy_value_C1:
	U_CRAZY value_C1
value_C1:
	C1
	FLAG2 return_from_value_C1_2 R_FLAG2
	FLAG5 return_from_value_C1_5 R_FLAG5
	RESET_FLAG1 ret_rst_val_c1_1 R_RESET_FLAG1
	RESET_FLAG2 ret_rst_val_c1_2 R_RESET_FLAG2
	RESET_FLAG3 ret_rst_val_c1_3


crazy_tmp:
	U_CRAZY tmp
tmp:
	C0
	FLAG3 return_from_tmp_3 R_FLAG3
	FLAG4 return_from_tmp_4

crazy_carry:
	U_CRAZY carry
exec_carry:
	R_MOVED
carry:
	CARRY
	U_NOP execution_not_jumped_to_carry
	U_NOP carry_was_not_set U_NOP carry_was_set
carry_was_set:
	MOVED return_carry_was_set
carry_was_not_set:
	MOVED return_carry_was_not_set
execution_not_jumped_to_carry:
	FLAG2 return_from_carry_2 R_FLAG2
	FLAG3 return_from_carry_reset R_FLAG3
return_carry_was_set:
	FLAG2 return_from_carry_was_set_2 R_FLAG2
return_carry_was_not_set:
	FLAG2 return_from_carry_was_not_set_2
// +-----------------------------------------+ \\
// | DECLARATION/INITIALIZATION OF VARIABLES | \\
// +-----------------------------------------+ \\
//
// variables (tmp1, tmp2, tmp3 and tmp4), their functions to modify them,
// and checking FLAGn for return selection.
stack_scratch_crazy:
	U_CRAZY stack_scratch
stack_scratch:
	C1
	PUSH_FLAG5 return_from_stack_scratch_2 R_PUSH_FLAG5
	RESET_FLAG1 ret_rst_ss_1 R_RESET_FLAG1
	RESET_FLAG2 ret_rst_ss_2 R_RESET_FLAG2
	RESET_FLAG3 ret_rst_ss_3


stack_scratch_1_crazy:
	U_CRAZY stack_scratch_1
stack_scratch_1:
	C1
	PUSH_FLAG5 return_from_ss1_2 R_PUSH_FLAG5
	RESET_FLAG1 ret_rst_ss1_1 R_RESET_FLAG1
	RESET_FLAG2 ret_rst_ss1_2 R_RESET_FLAG2
	RESET_FLAG3 ret_rst_ss1_3

stack_top_1_crazy:
	U_CRAZY stack_top_1
stack_top_1:
	C1
	PUSH_FLAG2 return_from_st1_2 R_PUSH_FLAG2
	PUSH_FLAG3 return_from_st1_3 R_PUSH_FLAG3
	PUSH_FLAG4 return_from_st1_4 R_PUSH_FLAG4
	RESET_FLAG1 ret_rst_st1_1 R_RESET_FLAG1
	RESET_FLAG2 ret_rst_st1_2 R_RESET_FLAG2
	RESET_FLAG3 ret_rst_st1_3

stack_top_crazy:
	U_CRAZY stack_top
stack_top:
	C1
	PUSH_FLAG2 return_from_stack_top_2 R_PUSH_FLAG2
	PUSH_FLAG3 return_from_stack_top_3 R_PUSH_FLAG3
	PUSH_FLAG4 return_from_stack_top_4 R_PUSH_FLAG4
	RESET_FLAG1 ret_rst_st_1 R_RESET_FLAG1
	RESET_FLAG2 ret_rst_st_2 R_RESET_FLAG2
	RESET_FLAG3 ret_rst_st_3

{
ENTRY:
	MOVED next_opcode
}{
next_opcode:
	R_MOVED
	IN ?- R_IN
	R_FLAG2
	MOVED crazy_value_C1
}{
return_from_value_C1_2:
	R_CRAZY R_MOVED
	R_FLAG2
	MOVED crazy_value
}{
return_from_value_2:
	R_CRAZY R_MOVED
	// dec(site2): value=B-1 (overflow IFF B==0x00).
	R_SUBROUTINE_FLAG2
	MOVED decrement_value
}{
return_from_decrement_value_1:
	// value=B.
	// dec(site2): value=B-1 (overflow IFF B==0x00).
	R_SUBROUTINE_FLAG2
	MOVED decrement_value
}{
return_from_decrement_value_2:
	NO_MORE_CARRY_FLAG disc_1
	MOVED dispatch_00
}{
disc_1:
	// dec(site3): value=B-2 (overflow IFF B==0x01).
	R_SUBROUTINE_FLAG3
	MOVED decrement_value
}{
return_from_decrement_value_3:
	NO_MORE_CARRY_FLAG disc_2
	MOVED dispatch_01
}{
disc_2:
	R_SUBROUTINE_FLAG4
	MOVED decrement_value
}{
return_from_decrement_value_4:
	OP1_FLAG return_from_dec_op1_3 R_OP1_FLAG
	NO_MORE_CARRY_FLAG disc_3
	MOVED dispatch_02
}{
disc_3:
	R_SUBROUTINE_FLAG1
	MOVED decrement_value
}{
return_from_disc_3:
	NO_MORE_CARRY_FLAG dispatch_fallback
	MOVED dispatch_03
}{
dispatch_03:
	R_MOVED
	R_SUB_FLAG
	R_CLEAN_FLAG
	MOVED reset_and_loop
}{
dispatch_00:
	HALT
}{
dispatch_01:
	IN ?- R_IN
	R_MOVED
	SLOT0_FLAG push_slot_1
	// Slot 0 (depth 0 -> 1):
	R_PUSH_FLAG5
	MOVED stack_scratch_crazy
}{
return_from_stack_scratch_2:
	R_CRAZY R_MOVED
	R_PUSH_FLAG2
	MOVED stack_top_crazy
}{
return_from_stack_top_2:
	R_CRAZY R_MOVED
	ADD_FLAG add_push0_done R_ADD_FLAG
	MOVED reset_and_loop
}{
push_slot_1:
	// Slot 1 (depth 1 -> 2):
	R_SLOT0_FLAG
	R_SLOT1_FLAG
	R_PUSH_FLAG5
	MOVED stack_scratch_1_crazy
}{
return_from_ss1_2:
	R_CRAZY R_MOVED
	R_PUSH_FLAG2
	MOVED stack_top_1_crazy
}{
return_from_st1_2:
	R_CRAZY R_MOVED
	MOVED reset_and_loop
}{
dispatch_02:
	R_MOVED
	R_CLEAN_FLAG
	MOVED reset_and_loop
}{
add_val_clean:
	OP1_FLAG add_val_clean_op1 R_OP1_FLAG
	R_ADD_FLAG
	ROT C2 R_ROT
	R_PUSH_FLAG3
	MOVED stack_top_1_crazy
}{
add_pop1_done:
	R_FLAG5
	MOVED crazy_value_C1
}{
return_from_value_C1_5:
	R_CRAZY R_MOVED
	R_FLAG5
	MOVED crazy_value
}{
return_from_value_5:
	R_CRAZY R_MOVED
	OP1_FLAG dec_op1 R_OP1_FLAG
	R_SUBROUTINE_FLAG5
	MOVED decrement_value
}{
return_from_dec_op2_1:
	OP1_FLAG return_from_dec_op1_1 R_OP1_FLAG
	NO_MORE_CARRY_FLAG op2_nonzero
	MOVED sum_is_2
}{
op2_nonzero:
	R_SUBROUTINE_FLAG6
	MOVED decrement_value
}{
return_from_dec_op2_2:
	OP1_FLAG return_from_dec_op1_2 R_OP1_FLAG
	NO_MORE_CARRY_FLAG op2_is_3
	SUB_FLAG diff_is_1 R_SUB_FLAG
	MOVED sum_is_2
}{
op2_is_3:
	R_OP1_FLAG
	R_CLEAN_FLAG
	MOVED reset_and_loop
}{
add_val_clean_op1:
	R_OP1_FLAG
	R_ADD_FLAG
	ROT C2 R_ROT
	R_PUSH_FLAG3
	MOVED stack_top_crazy
}{
add_pop0_done:
	R_FLAG5
	MOVED crazy_value_C1
}{
dec_op1:
	R_OP1_FLAG
	R_SUBROUTINE_FLAG5
	MOVED decrement_value
}{
return_from_dec_op1_1:
	R_OP1_FLAG
	R_SUBROUTINE_FLAG6
	MOVED decrement_value
}{
return_from_dec_op1_2:
	R_OP1_FLAG
	R_SUBROUTINE_FLAG4
	MOVED decrement_value
}{
return_from_dec_op1_3:
	NO_MORE_CARRY_FLAG check_add_or_sub_high
	SUB_FLAG diff_is_0 R_SUB_FLAG
	MOVED sum_is_5
}{
check_add_or_sub_high:
	SUB_FLAG diff_is_2_from_phase2 R_SUB_FLAG
	MOVED sum_is_7
}{
sum_is_7:
	R_MOVED
	R_OP1_FLAG
	R_SUBROUTINE_FLAG4
	MOVED sum_is_2
}{
diff_is_2_from_phase2:
	MOVED sum_is_2
}{
diff_is_0:
	R_OP1_FLAG
	R_SUBROUTINE_FLAG6
	MOVED sum_is_2
}{
diff_is_1:
	R_OP1_FLAG
	R_SUBROUTINE_FLAG5
	MOVED sum_is_2
}{
sum_is_5:
	R_MOVED
	R_OP1_FLAG
	MOVED sum_is_2
}{
sum_is_2:
	R_MOVED
	R_ADD_FLAG
	ROT C1 R_ROT
	R_RESET_FLAG1
	MOVED stack_scratch_crazy
}{
add_rst0_done:
	OP1_FLAG check_results R_OP1_FLAG
	ROT 6 R_ROT
	MOVED add_push_common
}{
check_results:
	SUBROUTINE_FLAG4 load_sum_7 R_SUBROUTINE_FLAG4
	SUBROUTINE_FLAG5 load_diff_1 R_SUBROUTINE_FLAG5
	SUBROUTINE_FLAG6 load_diff_0 R_SUBROUTINE_FLAG6
	ROT 15 R_ROT
	MOVED add_push_common
}{
load_sum_7:
	ROT 21 R_ROT
	MOVED add_push_common
}{
load_diff_1:
	ROT 3 R_ROT
	MOVED add_push_common
}{
load_diff_0:
	ROT 0 R_ROT
	MOVED add_push_common
}{
add_push_common:
	R_MOVED
	R_ADD_FLAG
	R_PUSH_FLAG5
	MOVED stack_scratch_crazy
}{
add_push0_done:
	R_SLOT1_FLAG
	ROT C1 R_ROT
	R_RESET_FLAG1
	MOVED stack_scratch_1_crazy
}{

dispatch_fallback:
	SLOT1_FLAG pop_slot_1
	// Fall-through: Slot 1 empty, pop Slot 0
	R_SLOT1_FLAG
	R_SLOT0_FLAG
	ROT C2 R_ROT
	R_PUSH_FLAG3
	MOVED stack_top_crazy
}{
return_from_stack_top_3:
	R_CRAZY R_MOVED
	ROT C2 R_ROT
	R_PUSH_FLAG4
	MOVED stack_top_crazy
}{
return_from_stack_top_4:
	R_CRAZY R_MOVED
	ADD_FLAG add_pop0_done R_ADD_FLAG

	OUT ?- R_OUT

	// Reset slot 0 to C1:
	ROT C1 R_ROT
	R_RESET_FLAG1
	MOVED stack_scratch_crazy
}{
ret_rst_ss_1:
	R_CRAZY R_MOVED
	ROT C2 R_ROT
	R_RESET_FLAG2
	MOVED stack_scratch_crazy
}{
ret_rst_ss_2:
	R_CRAZY R_MOVED
	ROT C0 R_ROT
	R_RESET_FLAG3
	MOVED stack_scratch_crazy
}{
ret_rst_ss_3:
	R_CRAZY R_MOVED
	ROT C1 R_ROT
	R_RESET_FLAG1
	MOVED stack_top_crazy
}{
ret_rst_st_1:
	R_CRAZY R_MOVED
	ROT C2 R_ROT
	R_RESET_FLAG2
	MOVED stack_top_crazy
}{
ret_rst_st_2:
	R_CRAZY R_MOVED
	ROT C0 R_ROT
	R_RESET_FLAG3
	MOVED stack_top_crazy
}{
ret_rst_st_3:
	R_CRAZY R_MOVED
	ADD_FLAG add_rst0_done R_ADD_FLAG
	MOVED reset_and_loop
}{
pop_slot_1:
	// Pop Slot 1:
	ROT C2 R_ROT
	R_PUSH_FLAG3
	MOVED stack_top_1_crazy
}{
return_from_st1_3:
	R_CRAZY R_MOVED
	ROT C2 R_ROT
	R_PUSH_FLAG4
	MOVED stack_top_1_crazy
}{
return_from_st1_4:
	R_CRAZY R_MOVED
	ADD_FLAG add_pop1_done R_ADD_FLAG

	OUT ?- R_OUT

	// Reset slot 1 to C1:
	ROT C1 R_ROT
	R_RESET_FLAG1
	MOVED stack_scratch_1_crazy
}{
ret_rst_ss1_1:
	R_CRAZY R_MOVED
	ROT C2 R_ROT
	R_RESET_FLAG2
	MOVED stack_scratch_1_crazy
}{
ret_rst_ss1_2:
	R_CRAZY R_MOVED
	ROT C0 R_ROT
	R_RESET_FLAG3
	MOVED stack_scratch_1_crazy
}{
ret_rst_ss1_3:
	R_CRAZY R_MOVED
	ROT C1 R_ROT
	R_RESET_FLAG1
	MOVED stack_top_1_crazy
}{
ret_rst_st1_1:
	R_CRAZY R_MOVED
	ROT C2 R_ROT
	R_RESET_FLAG2
	MOVED stack_top_1_crazy
}{
ret_rst_st1_2:
	R_CRAZY R_MOVED
	ROT C0 R_ROT
	R_RESET_FLAG3
	MOVED stack_top_1_crazy
}{
ret_rst_st1_3:
	R_CRAZY R_MOVED
	MOVED reset_and_loop
}{


reset_and_loop:
	R_MOVED
	ROT C1 R_ROT
	R_RESET_FLAG1
	MOVED crazy_value
}{
ret_rst_val_1:
	R_CRAZY R_MOVED
	ROT C2 R_ROT
	R_RESET_FLAG2
	MOVED crazy_value
}{
ret_rst_val_2:
	R_CRAZY R_MOVED
	ROT C0 R_ROT
	R_RESET_FLAG3
	MOVED crazy_value
}{
ret_rst_val_3:
	R_CRAZY R_MOVED
	ROT C1 R_ROT
	R_RESET_FLAG1
	MOVED crazy_value_C1
}{
ret_rst_val_c1_1:
	R_CRAZY R_MOVED
	ROT C2 R_ROT
	R_RESET_FLAG2
	MOVED crazy_value_C1
}{
ret_rst_val_c1_2:
	R_CRAZY R_MOVED
	ROT C0 R_ROT
	R_RESET_FLAG3
	MOVED crazy_value_C1
}{
ret_rst_val_c1_3:
	R_CRAZY R_MOVED
	ROT 3 R_ROT
	R_FLAG3
	MOVED crazy_carry
}{
return_from_carry_reset:
	R_CRAZY R_MOVED
	CLEAN_FLAG add_val_clean R_CLEAN_FLAG
	MOVED next_opcode
}{
}
{
decrement_value:
	// kill NO_MORE_CARRY_FLAG
	NO_MORE_CARRY_FLAG nomorecarrykilled_2 R_NO_MORE_CARRY_FLAG
nomorecarrykilled_2:
	// We have to set tmp to C0. It won't contain any trit that is 2, so we can just crazy C1 into tmp.
	R_MOVED
	ROT C1 R_ROT
	R_FLAG3 // set return flag
	MOVED crazy_tmp // crazy C1 into tmp variable to set it to C0

return_from_tmp_3:
	R_CRAZY
value_load_loop:
	ROT C2 R_ROT
jmp_into_loop_from_behind:
	R_MOVED
	R_FLAG8
	MOVED crazy_value

return_from_value_8:
	R_CRAZY R_MOVED
	LOOP2 value_loaded
	MOVED value_load_loop

value_loaded:
	LOOP2_2 jump_back_to_behind
	R_FLAG4 // set return flag
	MOVED crazy_tmp

return_from_tmp_4:
	R_CRAZY R_MOVED
	R_FLAG2 // set return flag
	MOVED crazy_carry

return_from_carry_2:
	R_CRAZY R_MOVED
	MOVED jmp_into_loop_from_behind

jump_back_to_behind:
	R_FLAG2
	MOVED exec_carry

return_from_carry_was_not_set_2:
	R_NO_MORE_CARRY_FLAG
return_from_carry_was_set_2:
	R_MOVED
	// rotate string_ptr until it has been rotated 10 times.
	// after rotating go to increment or rotate again corresponding to the NO_MORE_CARRY_FLAG
	R_FLAG9 // set return flag
	MOVED rot_value // rot string_ptr

return_from_value_9:
	R_MOVED R_ROT
	// exit loop after 5 times
	LOOP5 exit_inner_decrement_loop
	NO_MORE_CARRY_FLAG restore_no_more_carry_flag_and_rotate_value_2 R_NO_MORE_CARRY_FLAG
	MOVED decrement_value

exit_inner_decrement_loop:
	// exit loop after 2 times
	LOOP2_3 exit_decrement_loop
	NO_MORE_CARRY_FLAG restore_no_more_carry_flag_and_rotate_value_2 R_NO_MORE_CARRY_FLAG
	MOVED decrement_value

restore_no_more_carry_flag_and_rotate_value_2:
	R_NO_MORE_CARRY_FLAG
	MOVED return_from_carry_was_set_2

exit_decrement_loop:
	SUBROUTINE_FLAG1 return_from_disc_3 R_SUBROUTINE_FLAG1
	SUBROUTINE_FLAG2 return_from_decrement_value_2 R_SUBROUTINE_FLAG2
	SUBROUTINE_FLAG3 return_from_decrement_value_3 R_SUBROUTINE_FLAG3
	SUBROUTINE_FLAG4 return_from_decrement_value_4 R_SUBROUTINE_FLAG4
	SUBROUTINE_FLAG5 return_from_dec_op2_1 R_SUBROUTINE_FLAG5
	SUBROUTINE_FLAG6 return_from_dec_op2_2 R_SUBROUTINE_FLAG6
}
"""

def generate() -> str:
    return SOURCE_HELL

def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Unified Malbolge ALU mbir_alu.hell")
    parser.add_argument("-o", "--output", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generate(), encoding="utf-8")
    print(f"Generated {args.output} ({len(generate())} bytes)")

if __name__ == "__main__":
    main()
